### ISSUE TITLE
Chunk lines are not cleared after scroll window

### ISSUE THREAD

**Issue by ShiChenCong** [shellRaining/hlchunk.nvim#104] opened 2024-05-29 10:37 UTC
![Untitled](https://github.com/shellRaining/hlchunk.nvim/assets/22486446/3f3aeb2a-5242-4e56-99b2-9cfb4c12d9f9)

config file
```
  {
    "shellRaining/hlchunk.nvim",
    event = { "BufReadPre", "BufNewFile" },
    config = function()
      require("hlchunk").setup({
        chunk = {
          enable = true,
          style = {
            { fg = "#8c98a3" },
          },
        }
      })
    end
  },
```
nvim version: 0.10.0

**Comment by shellRaining** [comment] 2024-05-30 13:29
fixed in dev branch，temporarily close this issue.
And dev has many new feature (like animation for chunk), I will merge when it is stable

**Closed by shellRaining** 2024-05-30 13:29 UTC

**Comment by ShiChenCong** [comment] 2024-05-31 06:04
broken in `less` file in dev branch.

**Comment by shellRaining** [comment] 2024-05-31 07:44
It seems to be caused by the lack of a treesitter parser for `less`.

**Comment by ShiChenCong** [comment] 2024-05-31 08:50
How to disable plugin for some certain filetypes?

**Comment by shellRaining** [comment] 2024-05-31 10:31
If you simply do not want to see the information of notify, you can set `notify = false`

https://github.com/shellRaining/hlchunk.nvim/blob/main/docs/en/chunk.md#chunk_example1

if does want to disable, just set:

```lua
chunk = {
    enable = true,
    exclude_filetypes = {
        less = true,
    },
},
```
