### ISSUE TITLE
Mod names case change

### ISSUE THREAD

**Issue by davidosomething** [shellRaining/hlchunk.nvim#102] opened 2024-05-23 02:00 UTC
**Describe the bug**

previously had mods/chunk.lua
now have mods/Chunk/init.lua

same with other mods except `indent`

need to update readme to reflect new casing (`s/chunk/Chunk`) in setup options:

```
require('hlchunk').setup({ Blank = { enable = true }, Chunk = {...} })
```

**Comment by shellRaining** [comment] 2024-05-23 02:50
yes, readme should be updated, but previous config should work properly, uppercase is not needed (for me at least...)

**Comment by davidosomething** [comment] 2024-05-23 12:32
it would probably be filesystem dependent, whatever your harddrive is formatted to use
- typical mac filesystems support HFS and applefs case-sensitive AND case-insensitive
- typical windows is ntfs which is case-insensitive
- most linux users would be on case sensitive filesystem

**Comment by shellRaining** [comment] 2024-05-23 12:43
very thanks for your reminder!!! I can't imagine how many user has been affected. I will update the document as soon as possible.

**Comment by soifou** [comment] 2024-05-23 12:44
To go along with @davidosomething previous comment, the plugin crash on my case-sensitive file system:

```
Error detected while processing ColorScheme Autocommands for "*"..ColorScheme Autocommands for "*":                                           
Error executing lua callback: .../nvim/lazy/hlchunk.nvim/lua/hlchunk/mods/indent/init.lua:2: module 'hlchunk.mods.Indent.IndentConf' not found
```

Resolved with: 

```diff
diff --git a/lua/hlchunk/mods/indent/init.lua b/lua/hlchunk/mods/indent/init.lua
index 0bf83cc..319942e 100644
--- a/lua/hlchunk/mods/indent/init.lua
+++ b/lua/hlchunk/mods/indent/init.lua
@@ -1,5 +1,5 @@
 local BaseMod = require("hlchunk.mods.BaseMod")
-local IndentConf = require("hlchunk.mods.Indent.IndentConf")
+local IndentConf = require("hlchunk.mods.indent.IndentConf")
 local class = require("hlchunk.utils.class")
 local utils = require("hlchunk.utils.utils")
 local indentHelper = require("hlchunk.utils.indentHelper")
```

IMO, dealing with uppercase for file/folder structure is error prone...

**Closed** 2024-05-23 13:26 UTC

**Comment by shellRaining** [comment] 2024-05-23 13:50
@davidosomething @soifou Thank you very much for suggestions. I have temporarily resolved this issue by changing the directory name (and file name).

It has been more than a year since I started writing this plugin. It was originally created for learning Neovim plugin development, and the code quality was very poor at the beginning, and it is still so now, I have made many bad design decisions. Thank you for being able to tolerate and point out the mistakes I have made 🙏.

There are still many problems with this plugin, now working hard to solve them~

**Comment by sleeptightAnsiC** [comment] 2024-05-23 16:27
Thanks for addressing this quick @shellRaining 
I can confirm the plugin was broken on my Linux machine since yesterday.
Pulling latest patch fixed it https://github.com/shellRaining/hlchunk.nvim/commit/8aef948eeb0d2a4b32f911e93c7c33e04057cc20
