### ISSUE TITLE
priority of the indentation line is too high, sometimes covers the characters

### ISSUE THREAD

**Issue by Kicamon** [shellRaining/hlchunk.nvim#50] opened 2023-06-16 08:28 UTC
The priority of the indentation line is too high, sometimes it covers the characters and it's very uncomfortable. 

缩进线的优先级太高了，有时候会遮住字符，就很难受

**Comment by shellRaining** [comment] 2023-06-16 08:40
You haven't provided enough information, please give me a screenshot.

**Comment by Kicamon** [comment] 2023-06-16 08:53
like this, when i input "if", char "i" can't be seen at first
[gif](https://www.cnblogs.com/KicamonIce/p/17485995.html)

**Comment by shellRaining** [comment] 2023-06-16 08:54
the gif link can't open, and github can upload gif directly

**Comment by Kicamon** [comment] 2023-06-16 09:01
![Uploading 2023-06-16 16-44-57.gif…]()

**Comment by shellRaining** [comment] 2023-06-16 09:03
sry, but I still can't see the gif

<img width="580" alt="image" src="https://github.com/shellRaining/hlchunk.nvim/assets/111564053/6d75e464-ca55-4655-94b8-46c10b6be8cb">

maybe you need wait for a minute after paste into github

**Comment by Kicamon** [comment] 2023-06-16 09:05
![2023-06-16 16-44-57](https://github.com/shellRaining/hlchunk.nvim/assets/96783720/6aa95e3d-ce35-45ab-93da-6a9ec1ed453d)

fine now

**Comment by shellRaining** [comment] 2023-06-16 09:08
Is this problem occurring after formatting the code?

**Comment by Kicamon** [comment] 2023-06-16 09:09
no, befor formatting

**Comment by shellRaining** [comment] 2023-06-16 09:18
![Kapture 2023-06-16 at 17 16 29](https://github.com/shellRaining/hlchunk.nvim/assets/111564053/353bac11-50ed-4ac2-a098-6acc26d1cc47)

I'm sorry that I didn't reproduce this issue. Please make sure you are using the latest version of the plugin, because similar issues have indeed occurred before.

**Comment by Kicamon** [comment] 2023-06-16 09:43
OK! Thank u

**Comment by shellRaining** [comment] 2023-06-16 09:45
Has the issue been resolved? I will close this issue for now. If there are any other problems or if a stable reproduction method is found, please let me know for free~

**Closed by shellRaining** 2023-06-16 09:45 UTC
