### ISSUE TITLE
NeoVim crashes on current nightly build

### ISSUE THREAD

**Issue by biozz** [shellRaining/hlchunk.nvim#57] opened 2023-08-10 15:42 UTC
Hi! Thank you for this plugin, I am now switching from `mini.indentscope`, because it looks cool and works really fast. I had a small issue, which I would like to report here.

**Describe the bug**

Current nightly build of NeoVim crashes, when opening a file with a file type which is not supported by `hlchunk.nvim`.

```
Aug 10 17:46:47.214 ERROR Error: Process exited with error code 134
```

I feel like this is kind of related to #49.

When I open the same file on a stable build it works, but I get this message in the logs:

```
[hlchunk]: not have parser for make
```

I think the proper message for this in terms of grammar would be `no parser for <filetype>`.

Crashing aside, I would like to have an option to disable these messages or have a documentation in this repo about how to turn them off, as you mentioned in the linked issue:

> each plugin has a "notify" attribute that can be used to disable prompts

Where can I find this option?

**To Reproduce**

1. Use NeoVim nightly build
2. Open any file, which is not supported, ex. Makefile

**Expected behavior**

The file opens, there are no warnings about the missing filetype.

**Screenshots**
N/A

**Additional context**

```
NVIM v0.10.0-dev-798+g72e619ca9
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

Lazy package manager, with this config:

```lua
require("hlchunk").setup({
    blank = { enable = false },
})
```

**Comment by shellRaining** [comment] 2023-08-10 16:00
ok. Thanks for the details~

I'll try to fix this tomorrow

**Comment by shellRaining** [comment] 2023-08-11 01:53
I can't reproduce the issue of neovim crashing. Can you provide more information, such as a GIF or video?

Thank you for your reminder, the grammar issue has been fixed.

and to disable the notify, you can set like this

```lua
require("hlchunk").setup({
        chunk = {
            enable = true,
            notify = false,
            use_treesitter = true,
            textobject = "ic",
        },

        blank = { enable = false },
})
```

for more example of config of `hlchunk`, you can see [my config about hlchunk.nvim](https://github.com/shellRaining/nvim/blob/master/lua/conf/editor/hlchunk.lua), which contains nearly all feature that has been implemented

**Comment by shellRaining** [comment] 2023-08-11 08:41
Does nvim work properly  when you disable this plugin?

**Comment by biozz** [comment] 2023-08-11 08:57
Yes

**Comment by biozz** [comment] 2023-08-11 10:31
This works on nightly:

```lua
require("hlchunk").setup({
    chunk = {
        notify = false,
    },
    blank = { enable = false },
})
```

I think it is good to have an entire config example in readme, becuase I couldn't understand where to put `notify` option in the first place.

I also found the root cause, it is related to `folke/noice.nvim`. When I disable this plugin it work ok in nightly with `notify = true`.

Not sure what to do here. Up to you to close the issue. Thank you!

**Comment by shellRaining** [comment] 2023-08-11 10:51
Thanks for your suggestion. I have already added this part of the content, and in the future, I will continue to optimize the README to make it more understandable and easy to configure.

As for whether it is related to `noice.nvim`, I'm not sure because my configuration is similar to yours. We have the same Nvim version and are using both `noice.nvim` and `hlchunk.nvim`, testing with the same file type, but I haven't been able to reproduce this issue.

This issue may be related to the version of  plugins. I will close this issue for now, but please feel free to let me know if you encounter this problem again in the future.

**Closed by shellRaining** 2023-08-11 10:51 UTC
Labels: bug

**Comment by ch3n9w** [comment] 2024-03-30 02:43
The issue still exists, but I found something interesting. If the terminal size is small, the `[hlchunk.chunk]: no parser for make` will happened when I open a Makefile, which is not the case when the terminal size is relatively bigger.
